export { arrayOf, shape } from "prop-types"
export { ProfileType } from "./profile"
export { ProjectType } from "./project"
export { SocialType } from "./social"
export { WorkHistoryType } from "./work-history"
